---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: image-updater-registry-secret
  namespace: ai-viz
spec:
  encryptedData:
    .dockerconfigjson: AgCmYCNJC7hRvqpkWttWQh3405WmdR1gjKTOX7zpvFaaJrb8Y/8xwRDdG6MyUNjmSmzuO174VYgIXhXf4W9Nkth4tfL0JfSA+b0Gq8TJx9wcmrHeoW7r3ev23oHFrToSOD7R0OVttTPsduftrZebdfEhV9C6zeVDXSCj5XRRF/zW7USSVaI8RHl81dY2I/P1NtCMTXYjNUpHnedKHXjWNVbaZ1a2bLq/okyi0Nlz8zsUazs3XHXZOOS9aHxB2h1n8bq1HA76OwUjj0TuJliZ7IIfnreCbMYaWW76oxSIDgy5DjNNrC2vUeF4DNbmuhEaF9jDY9OqTDND5uB9W2rfwWjHPnI7AcdhqGYsPWnqCmXjuVRxggx2PZIldHiUsFtgT7YgYKbWxcsvCBt6IReb3QvgqMbOi3e8no0Fe7CnMG9aKEtm1/sGDvpuIdUT4FFuvHWwhsr3aCCdmP9rbpd/H4DacuIrSM/M63IEmGWq1buPQucoW5Dg0tlG30mYvdiKdDzcmPhJvO/sW7UIZZJDZQTjMEk9gQG5gXvdmG44i75EN/0oJ1nG6/ictShFu93ckfXvmBK9l+riEYkVMT/SnKXzKSZtO5Bnd3xsstbPDqjsJYhAnc8xc9fmWYqyLIA1MI9aduGor/QPlPApfaCZRMDsRGWOr4KzE63gfnas11coIyCDBPJhGrNudx+8eUT2ZPlbV4pAT+aBFxKzIDaNsvKgoRixAnUYtw72WewKtSm4p4zJ4HCkcPzcevHWlwdXCCQkh9Hk9EWovEO+NhfXvxqxbP0rE+78uF6JpzfmohmL1lC5cbv9LL8lY0lBPYR9v9cgjZTCGk8SLXLpeHGQCe/+6mpqsbKGEBe7DOIS57K6tLgrru/wnwvs11TrwiniwloIETuNCTLjVnGZEMb9TGSkVKDbHFimX/wDM8bam//O4o3ehTUDo864dmbzNttx6z6BcUaYjKkA6bmZBBFNU3x1/51fUxcKKTuc7YH9yRwknJpiExQkyHINTxgVQqdcVMloh23aW8a5INLdk48c7cP70MiHu1tYBjE3S1izyfYjuJeIRrSd6ZD9OAq+A/Y0JBEFX22BN8G95XpKqHQR/qcckr3+Xa0T
  template:
    metadata:
      name: image-updater-registry-secret
      namespace: ai-viz
    type: kubernetes.io/dockerconfigjson
