---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ai-viz-registry-secret
  namespace: ai-viz
spec:
  encryptedData:
    .dockerconfigjson: AgDI5NXl42QK/EGqVF1BiwHact8u6U8+cO6C/FBMFHSpXcAAzgmKFlXm6OuUxMvL4PdXqPBcOdhhM5qdzrbmVaE2mYYcjnW3q14ULhlEyTvRbs0KibEoRWVi8AcmwaCjD6nDkeGyPCf8v1ci4czdK+0hzpn9CrzU9hBo/2p4xQxS4ToGr0pq6tKf8PVKWTfwSttnIke+gpMDoJ8PuDxWZgQFjLligXDH5JeXgUDyIE+2OpqJA3GU5eHG9bwd7wLAabAAZhgv+eheVHNgwBmTtl9ubLEvdE8ixD2F9prWMziQAQwXQPITrqavmxTD/hEcQG2MYcJ9LwyBII2EdeyBkIeqgaFzUmpR1RK1P548A6M+oavB96w6q3Nd/VB4IxtebMHIFOsZpxXTRQQswQOKwrv0lMliswMRig3nOFg2HDgndZo7lidhPWgBHxqpnmQCwXMBjJqjJaIyzvp4lNFLnhKEAYB6lZ899DzATzE/K5fLPXt4oqBJf8JaUKcROWHoEul6WmmUBhQGJqmfNyiuRQ7jkAsjB1PZQM0CfwjNALxqzXG24pPIpsH1HcPJOe/GFCo4BW4XOhjhytg9xwJOPb3xtRcrcTABNjKpKnu/g9g8HFKeT90lw710HsArmdMIpGCVR8X2X3tpf7q5DiOG/XangSaX9W5Hbvvzrcp9/oUSpMElHSQOjmoaYadZL29WwACE/dcf8Ujg7hk4sBxD0Y2Br0Yx89ZCmC6+Z1Z0CpivlJod9UdQyb+b9JeiAOgdRZQUayWvN1TwkI/gPDjQUQlQ3F9bPUs18ReuRBmAeYmUnl9L5V6w2XjUimnr8fMQi4LoLYk8cih+XO4gdDsJXUu5VtufT8jujOod9S4VzI1QxnFXXYZhLp+NnHA0jiwi5yDSFpw0b9/FFBMksO2HWVhBosZRBpVeJSEMnNwvuU9ieb7C6uDFojJcTLRtklw9nRRuxSW6Xc2MpR0/kzNlQd9kTQdxzDNX2MkgHGkB+nVjlVnOcOMHGa4IDSIkzHCAhTwPUAZ/PP0sFRr9H0K/i4QVYsb3+4oKX4WpaW9AAoxLHU1hmYnyjvYjyUIsl3SQH8FjqbDBPeYQx7klQ9gSaysApguAnsPD
  template:
    metadata:
      name: ai-viz-registry-secret
      namespace: ai-viz
    type: kubernetes.io/dockerconfigjson
