---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ai-viz-registry-secret
  namespace: ai-viz
spec:
  encryptedData:
    .dockerconfigjson: AgAcuboSaLHhPkRFflwpcgkuYsNBvAtKFCVwPEm0fPn9i7Dm7bBmGK26lz2RfqEvsgKpJ1mW/pnzCe9DQsWm8iAl8H8QRDhPmBLAv1w/UKVf90oBcRhI4EsyX4rqgbYR3uo5rL1XGE/pU2Mhu8LYPSwoOlD9jHy5wfJadPn1/j5PVUEHdO5b+aY1JY6UuwtxcYxpIS1gDerkf7VjCnBSM3gy2zq1Ln46kqnOP6LSxwrGFmlomAZmn6FStgEP8AR0AaToAW92zQuCT+GIy/8OXnI6EQlnusz0xt4o8o/DujxGtkLW9Ypa45pTI5kCM+it1EqnZ5nWUwTJUTHudFNecdi3+vXD8HvQO5bnEKLSOQM92b6ISVy6bfGFQZdo0Qs6qFGqcf63SCHk8HHjyISiNfP1XFUl1LJ3njgNU9FrpkoLzmFZSFsDvYnFOz49/LG736vGwwlkyQWidLlvPn6nUjD4OoFGOwV4bTi50UTBOG2tv1Xe4s5zMyaIWgKfSsLV03Hr/ecmn0c6xe5y3MSmwQxwlD0Q4is4qiB3dxld96WmZT6IEflqJ8UwEoadDV9CrK9/4XIgZasW3JXDzW/CmRKLrRsLh3wuQVR8SK5D72km93mRzQ0OAkLwSx8g9yD11LIgBJH2T/F0nGakADYHuZkp0KGa3z8j7Uu2FST2MCEvuH1pWnT56aTqMoj+EFhjr34u+o1xxO/Ni+ZG+jcKSaORvyHftiZGsRldrqglz6V7IvsolqkchbLiq5PR8HXzeWVxxelRfwybwWENqSa6SY4kY4qBzGb72s9J9xYtksDfugEAan80Qs7+uU+Gy9R0YG/blojFgrFIAry7P3LYSzjayES7h+M69m9fDqfDcJ0d0tIoBUJFx0GRe9eD9nBtq1UYeNdxruNW8xPL5JaZdpikJBL4zZiEWeIP7U1RIH/ToUC2BNz4+TK/zQ==
  template:
    metadata:
      name: ai-viz-registry-secret
      namespace: ai-viz
    type: kubernetes.io/dockerconfigjson
