---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgDKqqABLr+BTz09WsMKlLnyjkr14sH6o2vzGm2C+3DTptxCWsBG1SqwRuhYgmirDD95wloPNQfe3xdp7HGPtmPNzvaVHxLdp8n2Z6lRd8pWV3mO4Oge5bR97MUSDCvX795S/Krb0KAqVpINBBCWYUjTAxFlCs5yiRIECIQ+zPk2W5d6kPhyrwXztYE0SIdWCI+qfGPhXP2C6/ung7ibvOMTWDPiCr9oq/dT/SWdHjmA0+JRwYvbZCACmw6ELFQWgySypNxjkletrgpBvaZb42dgW7Bxac4XUYzXh9JI51Hypj52f7qaogQ3s8NkOsE5TWFsvD9fsiVO7G1FwWkCQ/ivXPQDSkKTfx+OFDiVy32tH67RDsOMrav5hXc/vR4npr7fptoR/FCjfgp9PtTCFtuzcMzN2GYi/g9CmUp4hTHOs7E6uIM+XJS3sWhXbBaa3hrhPqbctWnO5oQlZcz/VU7DKCnDczK1Kt2C9zl2lTM3K5xTkiWWdG9dgXIxP48Udw6F3Wg6VWGh7DBHi/SJoMhOeB2MP3++tzIC64DBF0mdxhbknvLXTif/8xYvQjRY2QckMsfZABwal3rvGOjg+KT8i9eGMbEovemxc9SMb4h3c893uxoVDXwOhmkXuVyygpQdKDeBirEhDlMeN0BKPIY/jn4XUMcFT94rSjiYRbmNOW3tveh3ODUrTVzzmOgq30Q5KMYHSRwNNfRyUuFaxMSvd0mlZEloj4ikoNpYQde7fZAd3blqDVPS4d48xUzX4+kG/fjjL1KK5q29574qqHaTkEUP05tB+IbgVaOb7ME4N/jr/qiFn3iFcNKi/v0Ug7kLo/FnwPRoOeENw9/3tOH37IY4dO653MJwukOb63uovfDvkVcjsVt0UNJ1m/lItQ302eYYEe/45hxZcs4oUY5r+xLoi1m+cU9q9TgD+SvIGzaapsuCjB8heAJN9vT4iK9T6y3nszQaI5WTksKXNNNy5i6+eATF9wY22Q==
  template:
    metadata:
      name: ghcr-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
