---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: image-updater-registry-secret
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgAgDCQU6jXg12gnGy7AfVNnLB8AP8SL6vU5aP/gFyQQGVgxsq4UdTmGnrt04xtLjbcsYGm55NQHf39J2RzxkzJOfEOfV8CHRbw7tL+iSvovsTM8eEm89Mwhp4UVoHoD8ZGk9AxTm4BQ8UMkCT7W+MPBiZ82aZx3vyfWLCplYyXl+PdPt1iyjGtpjlnyZWTlGSSB8xuEfOcauDuqDcey9YJTffZURwOdknrjyIToHu1Z9JLuqFRNcqwGPhLKKJAcNWojoYZ+TpfK29yCwXkDRTVSIUhoFFtmXv1bDoqNv5eqwcFnzhK00OWA+zf2DIM3WdYrdpVuTBE6cyhyIFBiYEe5ZdyqDxQ9jhRuXs8erwUJKxg+mtfw6qRofpaKY3Hx+nKK15ktvRcZvVGMF0Akp4dX0qRLF6lOVMc8hRSIqsdFtG6MgyTdpRQGq7V2D+XoxsAOGyN0G0hexGkzzZp0oaAzGLieQlP29zxvxKGVfcYXNyjF6UR935PMd0L0guAhKVw+Av2izlO+dVbDWJlWkAokYIWm2of0wCjaUkCCC3bpEpArMhBpnW3F4/jWpiQExyFI+UOeSesD5XBI9EbS0WKRU4EoeBBcIrWsGHccELKKsooaMsekfqYdSot+JBPTxYqBuhbndG3cqpPUolQRQKSIgFDsDTCMoLY7Jzp3PJChDKDHcbzLAr7cRmSXHBtLYYixPv08g41br/f+MZHUumGnT0bUx8QMbRYySDp+2GzvkYN9yEILijEZ2D1AcByvO8Aqnj1JejIuGDQPP+YvdbI+28DoLdlDsVy5UWt0VGOpcxVIrgHWdDY/dA7luR7Z8JjWkyC0+0Z63hRoIldSyKE3/Yg73+dJ/fZIkaFKRVLFQ67qg0AA+Hg3GudDvwgCTd6p0rYkEeQ73m74Q13zXGauZzwJ2J3vN4bI+a3ugs4zEfbs+PFfSmalVQ==
  template:
    metadata:
      name: image-updater-registry-secret
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
