---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: image-updater-registry-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgB/kHV2gVAGvo03LvmV7qhwHROPlTbQvbs1t4p8KAm3dMnrc36UTeiXpXuYSjuzd3yDs8Gn4gp2eOC3A736L0Wo3UF0oDC2Vkrj5xQfA+c3v/Qd9sL3u8gtbn3J/iZOQ70g9Ttdjeo13wIv2JYzVgELwcCTJOIHAlmzX+5O7hIdGsMsa2P1Kia8w/0AiufvGoH/9v+bgXOz8c1qep9rBE9BaolcuudafFm9SlBBGIPt5CYSuwoDQ4DovTnGqF0SVSTiSAY1OcyokVLYCuhbMSLh9UOiudjdkG5eyHLkqR5H+oEB+EawALvTtwtw8DPBZuAJvlmhaqIN7vHSFDu9kLEd4v3ft36PqxXkhmlZuFSFNSknxXC8A7bObwKpi5jifFCpLEK4HszOyl1r3fmmr/eTANFOGAZChD4fpP5T8lgjQfUJt84LzG1CTopV6kl8r7XooHr929Io3dQN7S2ufj2N9ZHIKT0t2hoCoeEvRK9K1a5NkCgND4z33Hh29YRvqormnO4gIevWuyZX7+CwOTdVewPS4bXCrrCbIC/XwBaBriBcAY9YoIjPU14tb9YUiIr4V/Vp+BizPnK05fv9zhUC1z4MkVBIIzb+i76h8ZngfWoiktU+ilecP7g4Kzjp2xhs0djTlQZ/eHBPUcdf7aUXmzAzeX+2pRItPYtEl8SfZr5UTwbAPZGxt35NkwZ6vq1/L7+uqrO4Cweij7gS4u1sKCFrOsqyso6k1IsvgHH4UcoEM4EsidQv
    username: AgBCTHe/59KU0xdIeXv5oEvm9G7y6Q+zlO5YKDHn3TGXLe4XbCVO0DbiFS37FmvRWydl7dJOkdfWPpxjLFAAkSsD9axfXy83kjHg1SdQ4ci6rsCbpeBApEQ/P1gM0W/IRpQFR/Vcc9Md9qqNateda/6Oa/nEDSIutbrLbueBqFVbidtcXCHl1ops0X4fp/gyXbyeGuWaIJyjwiKhurNtDW5YG6RHB9l6eU6ti+ftCxmeYH+FG+jGcweiPsQhGDxwQsAqAK15ULFkkIeXJ1Im32c6ZWgQTPJYGOaQDlcKVsG/vGRN2TD8sl76OzSOtHxLaiL3BoKq0VwuYL0oRgG8b8Y2sPADQsOqDdzWtijhM2nVs7ECKH0ySgCfEmi1ahG68n5JTTiXRqeiRjeYTQpFZmTB/ENOaayzu2PYz72lgwzFY7stdTS8lLgu1I1SyOr5QOEzeb2cGmg/V6cY4btqy9Op+SOf3w/OTiSou2/P9xrSF4CBOvDnJ4ZiG6ogDOSZTOoCGV4Qk/5CPzR9FawpCGWffkitCdGikSuLn1cGV2mfzeKZq1paFB6i13A6nLoZb/f93eHvffHSbiLXWyDWCqSSKMWo9mF7naR+ARvEF9C08muyb+3PiH1HnbtXO8pOBEGWr4AzjiRf6n6ePA603wuJAU+Ue3aWLYIKFIOcpTeUpKeg4dWI7IEKj/eS5cGF9tVZJb9fN6TFdFLEknQ=
  template:
    metadata:
      name: image-updater-registry-secret
      namespace: argocd
