---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: image-updater-registry-secret
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgCE86H/cefmsuufe4xvKAhyNr+NLfd5CMqDjcCpbYFw8Rp9hG8xbkW266Rd8jwzILqIgq4CkA27phXIYZVgtsGOjmcBs+AXrnfatpdOsefIQfNxTGPXoe0iwD17Xqw9AGzJuTmNMWggzY3G7q4Gx2EHxdoiMiw720P4/9v7G2hlxCSyN9sKZ3UJWeg9PvYgJbqb5DHO6gpuDy8/02/KagneiTOrRUWqd4Bc/4qZ4oMTUIiaHBOxu9iCaQeERU8o3cHjjVJbztj393N45Mr69q+vQ0uQaulb38+/eMowMLV9TVfzrYvN17tQjXXkf+6NVILEdjyphr+vgX8s7OmrHvms2TUgBv8ZfKke+n8TPYkde883vZPgb+EorC6MNmXa24e0yIl4NL2xsoM6kEmme0gTE6bQXRU5VvmVDp2OoUOvtx/PdCWCxu2yn0YzhmUjuKP5vojUD9IjZcGZ5C6iMfWfP8CWaItTl6hWWfW+T96an/38wCI/gO5x5UCPZaZjz4NgIpZUuWQCYJ/NXa0xpBFnrTByiBrRQmNjYnDQcl7PtdIoa2B5oiKj55+z1sb049N7v7WhEmXjMFnYBgvcTkHg3CdZzuhuOBowztl2gn5LEtU6Y9LVFaPOSuhn9RDhwM9lPaEDj/XnJ+U/nQpFBT2PvKr5W19jq0kaejCdTjb6K64SIb+Ofv47b0YEpxELGKuU02dRS6B7t5hr3Tp9L1auSSgZFWZXyVTtvhGmsIySzRkE169WHUwBKYGybfMFefm1wLI2bJxqHZbFympOG773j0nAwqvt78f5Fzr1afpCR67qe1MwV7sDPDMHNesusqDjwKGH/GnK7KAk7w8TUkfOW/L9flFbh3UA1ESXGa0ZuAvRZnb3uexW4WBfrwaCZ2PjrInpSE93QqhbI3g2dT8qvIgEXzef+SuZBXXttg5mIYtgmPwliubRcA==
  template:
    metadata:
      name: image-updater-registry-secret
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
