---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: portfolio
spec:
  encryptedData:
    .dockerconfigjson: AgAAdqSAYzl9TAhI3JtVGxj1Ir6cuXIKzKbsCwYbqxrdCg52cixZIcltmqenbQMhdstsIEQuMy7TdpS6JA4bui6KJTrWGmLmRBTQpHxYkewLGirOEJlRB7AF0DzosF9ZJnbgxj7DSN8bES8wy8QVXkQTSNHqZRBcuhDSs8a20p5ycbMv1xl0fOwWP1Ohfj0v0hPmoy9vtVm6lO1l/iRm/EeIEUQkspAJXrDdW9JJft6qbwjfTBmFT15FO/HoEDWXgAFanvmikBUl3o3oun59RST1IBtSrCyewFtlUE+cDOwV4NRPtkr5CNkX9nbuM8eCdm6ll/c5Zjc/LR8WPHy7mnC6ViNy/h9u9YTOyRvHm+yqCMWjgxin9CJyYAAPG1HelSBuiwK7pe0idJKgYOJOfIhW6wm1PrVaO3GkjOomZWXIRZplvU/N9WW6dUiLDD9uHQVM+W6NYpq7DgQKh6IRbTH5gRmj39pV9Nolbb3uvCiLiR/Wzgsh+HmcEoAoN2NG3KJRC1LY9YXFWEG5KYXUVcy0p4pJwC+7KL2SgH9KRVuhE6viSb/EVyRu8GZ4kxNLX3JRejSQvLHKTpzsAWoR7MLDGvSnsA73Z5/0t7ZDv34tTFtiikJAn6WtHoASLgREgtgCPUJDeQNSLMCgRMuK5mhJUK6Dp5T3M5AJ/o53b8TIBdPFOW9PdDx2K+AUrNVIRvBPSWmdJg5PbERF5ouG1USrfHN1yNHiqT+0VGOwGrH3rYjvMZwFVwnohHqn+mx0c7wGxc1Ig9AxyCSPEckHoEbC93vZYa2SK9hCr82nhXYT4f0c5AHVEyVOxF5v23C+YL06wXCMephW1VH3p6BNn2GwEITisrO+cJcEhi7ou1vOzb20tSUczHBoZQ7nY1mqcs5iFGTnepFXuWkcbYA7tcKCzdzgtop1QeHPU+9z3c9k6cayiamM26pGEJVsOfBTSjOMG6U0xo+Jc9DPHOJNTr63SMv+jfN7eCgICg==
  template:
    metadata:
      name: ghcr-secret
      namespace: portfolio
    type: kubernetes.io/dockerconfigjson
