---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: portfolio-registry-secret
  namespace: portfolio
spec:
  encryptedData:
    .dockerconfigjson: AgDKSZj8mOg0812nsk+bAMN1rPyDXGWAtgJ6yOJBAAkQ7Oayp5ZdeycjbcwdpvsVrcg04j16ad+AO3YUeorRhVg3Z8TjFkBWYzDa30gYfQ8X11+Ik2q53gVk/vPodz/srXWBGr7QWOBwdvg8MHjyl7hgESZVvkI5tFkMFC9LSlOkOpx7qd6XQRLEy39S5Wi9Hsd/C2qoGy/o/rlhPupnBMwrlxp8FbL8whujuFSsj5tDUZSzGAwogSNIsSrg3Uz2Yn9w+k7cSmF8SCe/li37hxu4HnKQ8d599WC8NTZ+EvhIpUJyFu+kGtwBR113us6MWY0AKhnjBxw2x7ZGOMX8P/5s1PLfOh00lxOjv+rjSdo55P1DBE+uG/q9+h0h+PIvmX/cwQzJ83Msh1fs0D2n+b0FjpsV9b4DtuKIRmrzqv5mXZ7xK/O4dG1xlkguXbvnF0ETn7W9Bjm+j+dOXTV4gC82W3pD5OXHvzGVLuRloilEEVYrqYSCmYwsWwZUi1ehBkDBQGmOfmMsq2xUoDh+sgfFVwPepDBo9MaVIH0IZ1bHf1d0JrgwB6LE9nI+JNkoNdGThkbsVPFObY4AP7jaj0M/eG+U19ugWXAINBIaVbrrWFA78B5RDzWCSB1sOiUiqLh8BMJ1Bu2UbZK28RaAFdJ95rbNO9aOc3H+RuX/BVGRhsgeVmt4g63IOBC+R3rMBYpqfFlZ3wCNQ64kDtGUgsd0dcVLGGFC8pSF/XVzc5Zhd5O1zmB8DHHWgfltrg4pHCYOv+zHRag6VMXpWuOfPaELKZw4pVnRq4iqimrZA3G7audc0bYeraNU5R/cEX6K1OBRxPjPdDGvqdvtbu3VfMxf0OaeeToRoxGYTT102hhSksbUtJ422YbmwkyoIzbnMazMCbI/RN9y4q5iGBOrE4cnHk3ADVwlP6rtivIgMbpeU1bZ0MVWNnpxhl7lyf3w1UKR1C9TNYkn2QkK6L2I4xLQMCkf81xio1iT1A==
  template:
    metadata:
      name: portfolio-registry-secret
      namespace: portfolio
    type: kubernetes.io/dockerconfigjson
