---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-secret
  namespace: pihole
spec:
  encryptedData:
    password: AgBc3unUdY2xhNvAmwQ/5KzICdJnaguI1wujdRpLt+dmffyoObyOo0Vr/6Xg0VjUd9RhnqtXSBRzyvBum4rARaRSN5G19JgTXDEO1o7uBilqAayvBkMhbPkKssB99uMvTfdWBiDlLPEaJQSTB4fwxdkc1vV9bYLgHhE5bDAj4/j+MSf+nbHyzlmmfoxvOSyblVkb81hI7MfEuWIM+/lZXGLoitGhO7WIEdG36iC7pEftJsV6ovV1tRgYfzsO8kb5doDvwBMgScFP/hMIZlvbMUMnOPdUsCbwFPGYuEugCE+ry+g6i4IYoFF26sfDS36Fz/3+0k/RxvcD25zfx6UGR4m1ZbeAu70BAar7Yrc0EdbKGEnoSCTdpGjY+rZ+kXA9ALLJEPpwqQv/mbNgleKzqY1BsuTn52k0cAcwOw/on8tpjYq7KoLguIXWdGzrNfVzkDfWxASs55cbxyO/C1Qdg5HHfYymgpeB4IoF2cxrjic+F1cSprXF2vVY5mI1Gbb3etzVFWf4+sQQTxIKwyT0jr1DPxUggVcTFrBqk2IL/qr4N8miQmWv/hterGrl2WzL+Wh+uAmF9IaQyto2TLT/nWpmzSbVu+iGEmHZVhzS6NIjEm8Z/WTUuSSVl2jFPXVEodpy/ToHlBYfpSLQjkIdMgloAZYfFpuBPOOYVZU3J63uWG0RsZZ6CNsb9VR+sB6eYkv6KaxspH5sLQ==
  template:
    metadata:
      name: pihole-secret
      namespace: pihole
