apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octoprint
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: common
    targetRevision: 2.x.x
    helm:
      values: |
        image:
          repository: octoprint/octoprint
          tag: latest
        nodeSelector:
          node-type: pi
  destination:
    server: https://kubernetes.default.svc
    namespace: octoprint
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
