apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: portfolio-image-updater
  namespace: argocd
spec:
  namespace: argocd
  commonUpdateSettings:
    updateStrategy: digest
  writeBackConfig:
    method: argocd
  applicationRefs:
    - namePattern: "portfolio"
      images:
        - alias: ui
          imageName: ghcr.io/ryanhodge240/portfolio
