apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-cert
  namespace: traefik
spec:
  secretName: argo-lan-tls
  dnsNames:
    - argo.lan
  issuerRef:
    name: internal-ca-issuer
    kind: ClusterIssuer