apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - http-route.yaml
  - secrets/portfolio-registry-sealed-secret.yaml
  - secrets/image-updater-registry-sealed-secret.yaml
  - secrets/ai-viz-registry-sealed-secret.yaml

patches:
  - target:
      kind: Service
      name: argocd-server
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
  - path: config-maps.yaml
