apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale-subnet-router
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale-subnet-router
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["tailscale-state"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale-subnet-router
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tailscale-subnet-router
subjects:
  - kind: ServiceAccount
    name: tailscale-subnet-router
