---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-oauth
  namespace: tailscale
spec:
  encryptedData:
    TS_AUTHKEY: AgA39QBEtwxcvyOpVukYXB+wREguz1zSibgJSCXu0Z77wBb4LwZz3ulyTEYbyQ1QbeGG1/+x8E/hPqMMhKQzDQBZI1/7eIa8Gs1LZs39LzpqWiawK6/vHaSOemW2lUbuSf26J+0ebNsleWsFsQhTBT3O1ojlUmWGYaIxxsnGRYO9z9bCo6wdQseAVkt2cd1d0WubpyDLBaMZFjOmUm0CeYwJ9E07y15q6pjXLYO59uqfOeRYBez2r76JIWhGGepOYHbq1uqKwUa0zYDc+8C1OZY+dMxUKuQzs4XP3YY/MBGCd8VHyu9w76R12TfubKQKEE5l/7LgHbUbVItBFvscnjPHWZkSVpgJt7hkVMviOiTYMOEBQ1biYE6J5VKKzSL38n4R0BPor6COvtnPbLEO2qo/ySJqQERCGi2PrDE0vzkiG+dXrKznKzTmSSUralGJ4ayizH1XdieV3cQPYINFYBZX5o/oR+Dqu/54h2h3NGSggYgiMsvZOVA0Pqu7hTRJJ0/C5/eOciNnZSjlCa/0n+F7cN1PeeT0FwX8MJEfIz1Y1j6bvJIREpnZXJeBz4gs2Y82icByDFRnpwObdrrL0BvHBGHw9MKiXTVtYljGVF3TCnf30nR6gJd1lL43W7TaY/EtlcKeBM4la8ldJ3ch4n6hF/Tv14fGCXzkvNVXp/llh+rw2PVFEqo7ONgEaNqt9twR7FNawk7T0NWHqavJfPTBnVUwKfyH2JuGhpWuOT6DFTcEOIajvCL3aQt0iKbV9vrNiR49IeEFKrHifTTcVw==
  template:
    metadata:
      name: tailscale-oauth
      namespace: tailscale
