apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: health-check
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:ryanhodge240/HealthCheck.git
    targetRevision: main
    path: kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: health-check
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
