apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nicks-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: nicks-app=ghcr.io/ryanhodge240/nicks-app
    argocd-image-updater.argoproj.io/nicks-app.update-strategy: newest-build
    argocd-image-updater.argoproj.io/nicks-app.allow-tags: regexp:^[a-f0-9]{7,40}$
spec:
  project: default
  source:
    repoURL: git@github.com:ryanhodge240/NicksApp.git
    targetRevision: main
    path: kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: nicks-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
