apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: portfolio=ghcr.io/ryanhodge240/portfolio
    argocd-image-updater.argoproj.io/portfolio.update-strategy: digest
    argocd-image-updater.argoproj.io/portfolio.allow-tags: regexp:^latest$
spec:
  project: default
  source:
    repoURL: git@github.com:ryanhodge240/Portfolio.git
    targetRevision: main
    path: kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
